name: ðŸš€ 13.3 Deploy

on:
  workflow_dispatch:
  workflow_call:

jobs:
  deploy:
    uses: ./.github/workflows/verify_and_upload.yml
    with:
      version: "13.3"
      additional_architectures: ",cortex-m85"
    secrets: inherit
