name: ðŸš€ 14.2 Deploy

on:
  workflow_dispatch:
  workflow_call:

jobs:
  deploy:
    uses: ./.github/workflows/verify_and_upload.yml
    with:
      version: "14.2"
      additional_architectures: ",cortex-m85"
    secrets: inherit
